name: music
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  bloc:
  flutter_bloc:
  http:
  audioplayers: ^6.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  marquee: ^2.2.3
  loading_animation_widget: ^1.2.1
  curved_navigation_bar: ^1.0.6
  go_router: ^14.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#00FFFFFF"



flutter:
  uses-material-design: true

  assets:
    #Add assets from the images directory to the application.
    - assets/icon/
    - assets/animation/
